{% set name = "shellcheck" %}
{% set version = "0.7.1" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 50a219bde5c16fc0a40e2e3725b6c192ff589bc8a2569c32b62dcaece0495896

build:
  number: 1

  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack
    - {{ compiler('c') }}   # [linux]
    - {{ native }}binutils  # [not linux]
    - make                  # [linux]
    - perl                  # [linux]

  host:
    - gmp                   # [linux]

  run:
    - gmp                   # [linux]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
