{% set name = "shellcheck" %}
{% set version = "0.8.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: dad3a2140389f5032996e6d381a47074ddbad6e5d9155f72ef732952c8861a3b

build:
  number: 1 

  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack
    - {{ compiler('c') }}   # [linux]
    - {{ native }}binutils  # [not linux]
    - make                  # [linux]
    - perl                  # [linux]

  host:
    - gmp  # [linux]

  run:
    - gmp  # [linux]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # [not linux]
  license_file: LICENSE.txt  # [linux]
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
    - matthiasdiener
