{% set name = "shellcheck" %}
{% set version = "0.10.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz  # [not linux]
    sha256: 149ef8f90c0ccb8a5a9e64d2b8cdd079ac29f7d2f5a263ba64087093e9135050  # [not linux]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.x86_64.tar.xz  # [linux64]
    sha256: 6c881ab0698e4e6ea235245f22832860544f17ba386442fe7e9d629f8cbedf87  # [linux64]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.aarch64.tar.xz  # [aarch64]
    sha256: 324a7e89de8fa2aed0d0c28f3dab59cf84c6d74264022c00c22af665ed1a09bb  # [aarch64]

build:
  number: 0

  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack                     # [not linux]
    - {{ native }}binutils

  host:
    - gmp  # [osx]

  run:
    - gmp  # [osx]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # [not linux]
  license_file: LICENSE.txt  # [linux]
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
